### ISSUE TITLE
Concatenated alternate spellings

### ISSUE THREAD

**Issue by antecedent** [unimorph/dan#1]
These are probably scraping errors; I am sure Danish does not have such quirky instances of reduplication:

- _bægerenebægrene_ and similar forms under _bæger_
- _fignernefigenerne_ and similar forms under _figen_
- _hammernehamrene_ and similar forms under _hammer_
- _lagenernelagnerne_ and similar forms under _lagen_
- _næbenenæbbene_ and similar forms under _næb_
- _ørkenerneørknerne_ and similar forms under _ørken_
- _pebernepebrene_ and similar forms under _peber_
- _rommernerom'erne_ and similar forms under _rom_
- _tigernestigrenes_ and similar forms under _tiger_

**Comment by aryamccarthy** [comment]
Thanks! Do you mind submitting a PR?

**Comment by antecedent** [comment]
I will; however, these seem to be spelling variants (_bægerene_ ~ _bægrene_ etc). I assume I'll keep just the former ones in the pairs, but that might or might not be the best choice.

**Comment by aryamccarthy** [comment]
Sounds good.
